version: '3'
services:
  mediaelch:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'USER_ID=${USER_ID}'
      - 'GROUP_ID=${GROUP_ID}'
      - 'TAKE_CONFIG_OWNERSHIP=${TAKE_CONFIG_OWNERSHIP}'
      - 'CLEAN_TMP_DIR=${CLEAN_TMP_DIR}'
      - 'SECURE_CONNECTION=${SECURE_CONNECTION}'
      - 'VNC_PASSWORD=${VNC_PASSWORD}'
    volumes:
      - '${VOLUME_CONFIG}:/home/mediaelch/.config/kvibes'
    ports:
      - '5801:5800'
      - '5901:5900'
